//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchCategory
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Category Category { get; set; }
    }
}
