//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchItem()
        {
            this.ItemEvals = new HashSet<ItemEval>();
        }
    
        public long ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Notes { get; set; }
        public Nullable<long> UserLogID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Item Item { get; set; }
        public virtual UserLog UserLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemEval> ItemEvals { get; set; }
    }
}
