//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public long ID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string TableName { get; set; }
        public Nullable<long> TableID { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<double> EvalDegree { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
