//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraCost
    {
        public int ID { get; set; }
        public string ExtraTitle { get; set; }
        public Nullable<decimal> ExtraValue { get; set; }
        public Nullable<long> UserLogID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
