//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtraCost()
        {
            this.InvoiceExtraCosts = new HashSet<InvoiceExtraCost>();
        }
    
        public int ID { get; set; }
        public string ExtraTitleAr { get; set; }
        public string ExtraTitleEn { get; set; }
        public Nullable<decimal> ExtraValue { get; set; }
        public Nullable<long> UserLogID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExtraCost> InvoiceExtraCosts { get; set; }
    }
}
