//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceBranchServed
    {
        public long ID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<bool> Served { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<long> UserLogID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual UserLog UserLog { get; set; }
    }
}
