//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEval
    {
        public int ID { get; set; }
        public Nullable<long> BranchItemID { get; set; }
        public Nullable<int> EvalDegree { get; set; }
    
        public virtual BranchItem BranchItem { get; set; }
    }
}
