//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurghadaMarketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferItem
    {
        public long ID { get; set; }
        public Nullable<long> OfferID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
